### ISSUE TITLE
LICENSE file에 copyright 기입

### ISSUE THREAD

**Issue by DogFooter** [lawrence-kaybob/weblockly#12]
weblockly에 대한 copyright 작성이 없었어요

**Comment by lawrence-kaybob** [comment]
PR #13 에 반영!

**Comment by lawrence-kaybob** [comment]
LICENSE 파일에 이름은 다 기입이 되어 있긴한데 연락처가 없는 상황이라... 우선 이 이슈는 닫고 나중에 필요하면 다시 여는 것으로!!
