### ISSUE TITLE
Using xml (toolbox layout) from outside file  in html

### ISSUE THREAD

**Issue by credtiger96** [lawrence-kaybob/weblockly#2]
I think all of xml writen in pug is not clear to see. 

i want to import xml in html like other script file.

**Comment by lawrence-kaybob** [comment]
[view/index.js](https://github.com/lawrence-kaybob/weblockly/blob/master/public/javascripts/view/index.js#L11)에서 볼 수 있듯이 XML 파일을 따로 빼놓고 이를 Ajax로 받아와서 HTML 내에 낑겨 넣어줬음
